/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.byteparity.portal.portlet.storelocator.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StoreInformation service. Represents a row in the &quot;ByteParity_StoreInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.byteparity.portal.portlet.storelocator.model.impl.StoreInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.byteparity.portal.portlet.storelocator.model.impl.StoreInformationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreInformation
 * @see com.byteparity.portal.portlet.storelocator.model.impl.StoreInformationImpl
 * @see com.byteparity.portal.portlet.storelocator.model.impl.StoreInformationModelImpl
 * @generated
 */
@ProviderType
public interface StoreInformationModel extends BaseModel<StoreInformation>,
	ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a store information model instance should use the {@link StoreInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this store information.
	 *
	 * @return the primary key of this store information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store information.
	 *
	 * @param primaryKey the primary key of this store information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this store information.
	 *
	 * @return the uuid of this store information
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this store information.
	 *
	 * @param uuid the uuid of this store information
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the store ID of this store information.
	 *
	 * @return the store ID of this store information
	 */
	public long getStoreId();

	/**
	 * Sets the store ID of this store information.
	 *
	 * @param storeId the store ID of this store information
	 */
	public void setStoreId(long storeId);

	/**
	 * Returns the store name of this store information.
	 *
	 * @return the store name of this store information
	 */
	@AutoEscape
	public String getStoreName();

	/**
	 * Sets the store name of this store information.
	 *
	 * @param storeName the store name of this store information
	 */
	public void setStoreName(String storeName);

	/**
	 * Returns the address1 of this store information.
	 *
	 * @return the address1 of this store information
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this store information.
	 *
	 * @param address1 the address1 of this store information
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this store information.
	 *
	 * @return the address2 of this store information
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this store information.
	 *
	 * @param address2 the address2 of this store information
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this store information.
	 *
	 * @return the city of this store information
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this store information.
	 *
	 * @param city the city of this store information
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this store information.
	 *
	 * @return the state of this store information
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this store information.
	 *
	 * @param state the state of this store information
	 */
	public void setState(String state);

	/**
	 * Returns the country of this store information.
	 *
	 * @return the country of this store information
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this store information.
	 *
	 * @param country the country of this store information
	 */
	public void setCountry(String country);

	/**
	 * Returns the zip of this store information.
	 *
	 * @return the zip of this store information
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this store information.
	 *
	 * @param zip the zip of this store information
	 */
	public void setZip(String zip);

	/**
	 * Returns the phone of this store information.
	 *
	 * @return the phone of this store information
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this store information.
	 *
	 * @param phone the phone of this store information
	 */
	public void setPhone(String phone);

	/**
	 * Returns the latitude of this store information.
	 *
	 * @return the latitude of this store information
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this store information.
	 *
	 * @param latitude the latitude of this store information
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this store information.
	 *
	 * @return the longitude of this store information
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this store information.
	 *
	 * @param longitude the longitude of this store information
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the group ID of this store information.
	 *
	 * @return the group ID of this store information
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this store information.
	 *
	 * @param groupId the group ID of this store information
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this store information.
	 *
	 * @return the company ID of this store information
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this store information.
	 *
	 * @param companyId the company ID of this store information
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this store information.
	 *
	 * @return the created by of this store information
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this store information.
	 *
	 * @param createdBy the created by of this store information
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the create date of this store information.
	 *
	 * @return the create date of this store information
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this store information.
	 *
	 * @param createDate the create date of this store information
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this store information.
	 *
	 * @return the modified date of this store information
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this store information.
	 *
	 * @param modifiedDate the modified date of this store information
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StoreInformation storeInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StoreInformation> toCacheModel();

	@Override
	public StoreInformation toEscapedModel();

	@Override
	public StoreInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}